# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main, 'release/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build-on-ubuntu-latest:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 18.0.2+101
          distribution: temurin
      - name: Set up Xvfb
        run: |
        sudo apt-get install xvfb
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: mkdir staging && cp target/*.jar target/*.exe staging  
      - uses: actions/upload-artifact@v4
        with:
          name: Package (.jar and .exe)
          path: staging

  build-on-macos-latest:
    
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 18.0.2+101
          distribution: temurin
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: mkdir staging && cp target/*.dmg staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package (.dmg)
          path: staging
